import { type CollectionEntry, getCollection } from 'astro:content';

export type WorkEntry = CollectionEntry<'work'>;

export const contentSlug = (id: string) => id.replace(/\.(md|mdx)$/i, '');
export const slugifyTag = (tag: string) => tag.toLowerCase().replace(/[^a-z0-9]+/g, '-');

export const profileData = {
	name: 'Tajinder Singh',
	role: 'Solutions Architect',
	tagline: 'Architecture-first systems for edge, automation, and data',
	avatarUrl: '/images/tajinder-singh-portrait.jpg',
	location: 'United Kingdom',
} as const;

export const ctaData = {
	primary: { label: 'View Work', path: '/work' },
	secondary: { label: 'Contact', path: '/contact' },
} as const;

export const aboutData = {
	name: 'Tajinder Singh',
	headline: 'Solutions Architect',
	bio: 'Solutions architect focused on edge verification, automation-first flows, and operationally reliable data systems.',
	skills: ['Cloudflare Workers', 'n8n', 'TypeScript', 'Meilisearch', 'Xano'],
	focusAreas: ['Edge systems', 'Automation', 'Search and data platforms'],
	avatarUrl: '/images/tajinder-singh-portrait.jpg',
	social: [
		{ label: 'GitHub', url: 'https://github.com/tajbuilds' },
		{ label: 'LinkedIn', url: 'https://www.linkedin.com/in/taj-tajinder/' },
	],
} as const;

export const contactData = {
	email: 'contact@tajs.io',
	formPath: '/api/contact',
	turnstileRequired: true,
	links: [{ label: 'LinkedIn', url: 'https://www.linkedin.com/in/taj-tajinder/' }],
} as const;

export const privacyData = {
	lastUpdated: '8 March 2026',
	introduction: [
		'This Privacy Policy explains how the Taj Builds mobile application and the tajs.io website handle information.',
		'The website and mobile application are operated by Tajinder Singh as a personal portfolio to showcase software architecture, engineering projects, and technical case studies.',
		'We respect your privacy and are committed to protecting any information you may provide while using our services.',
	],
	sections: [
		{
			title: 'Information We Collect',
			items: [
				{
					heading: 'Personal Information',
					paragraphs: [
						'The website and mobile application do not require user accounts and do not collect personal information directly from users for browsing.',
						'You can browse the portfolio, case studies, and technical content without providing personal data.',
					],
				},
				{
					heading: 'Automatically Collected Information',
					paragraphs: [
						'When accessing the website or app, certain technical information may be collected automatically by the hosting infrastructure to ensure the service operates correctly.',
						'This information is used only for operational, security, and performance purposes.',
					],
					bullets: [
						'IP address',
						'Browser or device type',
						'Operating system',
						'Pages visited',
						'Time and date of requests',
					],
				},
			],
		},
		{
			title: 'Third-Party Services',
			paragraphs: [
				'The portfolio uses trusted third-party services to operate the website and infrastructure. These services may process limited technical information required for functionality.',
				'Each third-party service operates under its own privacy policy.',
			],
			bullets: [
				'Cloudflare - content delivery, caching, and security',
				'GitHub - source code hosting',
				'Resend or email delivery services - contact form processing',
				'Cloudflare Turnstile - spam and bot protection',
			],
		},
		{
			title: 'Cookies and Tracking',
			paragraphs: [
				'The website may use minimal cookies required for security and functionality, such as bot protection or performance optimisation.',
				'No advertising cookies or behavioural tracking technologies are used.',
			],
		},
		{
			title: 'Data Storage',
			paragraphs: [
				'The portfolio site and mobile application do not maintain a user account database.',
				'Technical logs generated by hosting providers may be retained for security, troubleshooting, and operational monitoring.',
			],
		},
		{
			title: "Children's Privacy",
			paragraphs: [
				'The website and mobile application are not directed at children under the age of 13.',
				'No personal information is knowingly collected from children.',
			],
		},
		{
			title: 'Security',
			paragraphs: [
				'Reasonable technical and organisational measures are implemented to protect the website and infrastructure from unauthorised access or misuse.',
				'However, no system can guarantee absolute security.',
			],
		},
		{
			title: 'Changes to This Policy',
			paragraphs: [
				'This Privacy Policy may be updated periodically to reflect changes in services or legal requirements.',
				'Updates will be posted on this page with an updated revision date.',
			],
		},
	],
	contact: {
		name: 'Tajinder Singh',
		website: 'https://tajs.io',
		email: 'contact@tajs.io',
	},
} as const;

export const getPublishedWorkEntries = async () =>
	(await getCollection('work'))
		.filter((entry) => !entry.data.draft)
		.sort((a, b) => b.data.date.valueOf() - a.data.date.valueOf());

export const getFeaturedWorkEntries = async (limit = 4) =>
	(await getPublishedWorkEntries()).filter((entry) => entry.data.featured).slice(0, limit);

export const getPublishedWorkTags = async () =>
	Array.from(
		new Set((await getPublishedWorkEntries()).flatMap((item) => item.data.tags).map((tag) => tag.trim())),
	).sort((a, b) => a.localeCompare(b));

export const getWorkEntryBySlug = async (slug: string) =>
	(await getPublishedWorkEntries()).find((entry) => contentSlug(entry.id).toLowerCase() === slug.toLowerCase());
